[package]
name = "mwheel-log"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "4.0.1"
once_cell = "1.16.0"
parking_lot = "0.12.1"
rdev = "0.5.2"
